version: '3'

services:
  db:
    image: mysql
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - spring-network
    ports:
      - "3306:3306"

networks:
  spring-network:
    driver: bridge